- name: Configure service accounts
  hosts: ipaservers
  become: true
  gather_facts: true
  tags: user_setup
  vars_files:
    - vars/secrets.yml
    - vars/vars.yml
  tasks:
    - name: Add service accounts
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        users:
          - name: authentik_svc
            first: Authentik
            last: ServiceAccount
            password: "{{ authentik_svc_password }}"
            passwordexpiration: "3023-01-19 23:59:59"
            userclass: service_account
          - name: veyon_svc
            first: Veyon
            last: ServiceAccount
            password: "{{ veyon_svc_password }}"
            passwordexpiration: "3023-01-19 23:59:59"
            userclass: service_account
        update_password: on_create

    - name: Add service accounts group
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        name: service_accounts
        description: Group containing all service accounts
        user:
          - authentik_svc
          - veyon_svc
        state: present

    - name: Add roles to service accounts
      freeipa.ansible_freeipa.iparole:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        name: User Admin Service Account
        description: Administrative role for service accounts to manage users
        privilege: "User Administrators"
        user:
          - authentik_svc
        state: present

    - name: Allow Authentik service account to change passwords without prompting for a reset
      community.general.ldap_attrs:
        bind_dn: "cn=Directory Manager"
        bind_pw: "{{ vault_ipadm_password }}"
        dn: cn=ipa_pwd_extop,cn=plugins,cn=config
        attributes:
          passSyncManagersDNs: uid=authentik_svc,cn=users,cn=accounts,dc=ipa,dc=rischool,dc=ru
        server_uri: ldap://localhost
        state: present
