- name: Run full setup for FreeIPA
  hosts: ipaclients
  become: true
  gather_facts: true
  vars_files:
    - vars/secrets.yml
    - vars/vars.yml

  pre_tasks:
    - name: Ensure hostname has domain attached
      ansible.builtin.hostname:
        name: "{{ ansible_facts['hostname'] }}.{{ domain_name }}"
      when: ansible_facts['fqdn'] != (ansible_facts['hostname'] + '.' + domain_name)

    - name: Input localansible fact directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create localansible fact file for pupil workstations
      community.general.ini_file:
        path: /etc/ansible/facts.d/workstation.fact
        section: role
        option: name
        value: pupil
        mode: '0644'
      when: "'pupil_workstations' in group_names"

    - name: Create localansible fact file for staff workstations
      community.general.ini_file:
        path: /etc/ansible/facts.d/workstation.fact
        section: role
        option: name
        value: staff
        mode: '0644'
      when: "'staff_workstations' in group_names"


  roles:
    - role: ipaclient
      state: present


  tasks:
    - name: Create /opt/ansible directory
      ansible.builtin.file:
        path: /opt/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Input ansible-pull vault password
      ansible.builtin.copy:
        dest: /opt/.vault-password
        owner: root
        group: root
        mode: '0600'
        content: "{{ ansible_pull_vault_password }}"
      no_log: true


    - name: Install ansible & git
      ansible.builtin.package:
        name:
          - ansible
          - git
        state: present

# Now this playbook can be chained with the ansible-pull command
# The full command should look like this:
# ansible-playbook setup_client.yml && ansible ipaclients -m command -a \
# "ansible-pull -U https://github.com/passmore-ris/ansible_pull_config.git -d /opt/ansible \
# --vault-password /opt/ansible/.vault-password" -b
