[all:vars]
ipa_server_ip = "192.168.122.4"
ipa_server_fqdn = "dc1.ipa.rischool.ru"
domain = "ipa.rischool.ru"
realm = "IPA.RISCHOOL.RU"
ansible_user=root

[ipaservers]
"{{ ipa_server_fqdn }}" ansible_host="{{ ipa_server_ip }}" #ansible_user=root

[ipaservers:vars]
#ansible_user=root
ipaadmin_password="{{ vaultipaadmin_password }}"
ipadm_password="{{ vault_ipadm_password }}"
ipaserver_domain="{{ domain }}"
ipaserver_realm="{{ realm }}"
ipaserver_setup_dns=yes
ipaserver_forwarders="9.9.9.9,149.112.112.112"

[ipaclients:children]
pupil_workstations
staff_workstations


[pupil_workstations]
debian-pupil.ipa.rischool.ru ansible_host=192.168.122.234

[staff_workstations]
debian-staff.ipa.rischool.ru ansible_host=192.168.122.99

[nfsserver]
nfs.ipa.rischool.ru ansible_host=192.168.122.22

[ipaclients:vars]
ipaservers="{{ ipa_server_fqdn }}"
ipaadmin_principal=admin
ipaadmin_password="{{ vault_ipaadmin_password }}"
ipaclient_domain="{{ domain }}"
ipaclient_realm="{{ realm }}"
ipaclient_configure_dns_resolver=yes
ipaclient_dns_servers="{{ ipa_server_ip }}"
ipaclient_force_join=yes
ipaclient_mkhomedir=yes
ipaclient_principal=admin
ipaclient_password="{{ vault_ipaadmin_password }}"
ipaclient_automount_location="default"
#ipaclient_otp=thisisyourpassword
#ipaclient_use_otp=yes
ipaclient_allow_repair=yes
#ipaclient_keytab=/tmp/krb5.keytab
#ipaadmin_principal=admin
#ipaadmin_password=password1
#ipaclient_force_join=yes
#ipaclient_kinit_attempts=3